name: CI

on:
  push:
  pull_request:

env:
  PYTHON_VERSION: "3.12"
  PROJECT_DIR: Wanderly

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m  pip install -r "${PROJECT_DIR}/dev-requirements.in"

      - name: Run tests with coverage
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -o pipefail
          coverage run -m pytest || status=$?
          status=${status:-0}

          if [ "$status" -eq 5 ]; then
            echo "pytest exited with code 5 (no tests collected); treating as success."
          elif [ "$status" -ne 0 ]; then
            exit "$status"
          fi

          coverage report -m | tee coverage.txt || true

      - name: Analyze code with pylint
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          DJANGO_SETTINGS_MODULE: Wanderly.settings
        run: | 
          pylint --load-plugins pylint_django . \
              --disable=wrong-import-position,pointless-string-statement \
              --ignore=tests,tools \
              --ignore-patterns="__init__\.py|asgi\.py|manage\.py|settings\.py|conftest\.py" \
              | tee pylint-report.txt
          if [ ! -s pylint-report.txt ]; then
            echo "Pylint score 10.00/10" > pylint-report.txt
          fi

      - name: Post pylint report comment
        if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: Wanderly/pylint-report.txt
      
      - name: Post coverage report comment
        if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python tools/post_coverage_comment.py coverage.txt
      
      - name: Run pip-audit On Lock File
        run: |
          pip-audit -r Wanderly/requirements.txt -f json -o pip-audit-report.json

      - name: Post pip-audit Report Comment
        if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python tools/post_coverage_comment.py pip-audit-report.json

      - name: Run Bandit Security Linting
        run: |
          bandit -r Wanderly -c bandit.yaml -lll
